version: "3.7"

services:
  hat:
    build:
      context: .
      dockerfile: Dockerfile
    #image: shdv/hat.sh:latest
    container_name: hat
    hostname: hat
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    ports:
      - '127.0.0.1:3991:80'
    volumes:
      - ./src:/usr/share/nginx/html/out
